serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: iris-api
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: default

          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: iris-api

          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8000"

        metrics_path: /metrics
        scrape_interval: 5s